### ISSUE TITLE
Extension failed to activate because it couldn't find typescript

### ISSUE THREAD

**Issue by Suarez1006** [ipatalas/vscode-postfix-ts#79]
It was working and vscode updated and it broke.
Attached the log reporting that says that couldn't find typescript.
The package.json has typescript as a dependency but vscode is set to use the bundled typescript instead of the package.json one

```
[2022-09-21 10:18:16.355] [exthost] [error] Activating extension ipatalas.vscode-postfix-ts failed due to an error:
[2022-09-21 10:18:16.355] [exthost] [error] Error: Cannot find module 'typescript'
Require stack:
- c:\Users\Killa\.vscode\extensions\ipatalas.vscode-postfix-ts-1.11.1\out\src\postfixCompletionProvider.js
- c:\Users\Killa\.vscode\extensions\ipatalas.vscode-postfix-ts-1.11.1\out\src\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at Module._load (node:internal/modules/cjs/loader:832:27)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at s._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:14538)
	at p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62866)
	at E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\Killa\.vscode\extensions\ipatalas.vscode-postfix-ts-1.11.1\out\src\postfixCompletionProvider.js:5:12)
	at u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at s._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:14538)
	at p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62866)
	at E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\Killa\.vscode\extensions\ipatalas.vscode-postfix-ts-1.11.1\out\src\extension.js:14:37)
	at u._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at s._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:14538)
	at p._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62866)
	at E._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at b._loadCommonJSModule (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:64346)
	at b._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14941)
	at b._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:13880)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8166)
	at async E._initialize (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7530)
```

**Comment by ipatalas** [comment]
Oooops. I figured what happened. This was first release published from CI and apparently there is a bug there, fixing manually. New release should be there in few minutes.

**Comment by ipatalas** [comment]
All right, new version released. Sorry for inconvenience!

**Comment by Suarez1006** [comment]
It's working now, thanks you very much
